# movieexplorer-frontend/Dockerfile

# Build stage
FROM node:20 AS build
WORKDIR /app
COPY . .

# Copy env file explicitly
COPY .env.production .env.production

RUN npm install && npm run build

# Serve stage
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]


# Local dotnet test - need to run backend and frontend
#cd ../movieexplorer-frontend
#npm run dev
#then view http://localhost:5173/ in browser



# To build and run this Dockerfile, use the following commands:
# docker build --platform linux/amd64 -t movieexplorer-frontend .
# docker run --rm -p 8080:8080 movieexplorer-frontend


# To push to acr
#     az acr login --name lewisacr
#     docker tag movieexplorer-frontend lewisacr.azurecr.io/movieexplorer-frontend:latest
#     docker push lewisacr.azurecr.io/movieexplorer-frontend:latest


# npm run build
# docker build --platform linux/amd64 -t movieexplorer-frontend .
# docker tag movieexplorer-frontend lewisacr.azurecr.io/movieexplorer-frontend:latest
# docker push lewisacr.azurecr.io/movieexplorer-frontend:latest


