# A gated pipelines to destroy all infrastructure created by the deploy-infra pipeline.

trigger:
  none

stages:
  - stage: DestroyInfra
    jobs:
    - job: Terraform_Destroy_Job
      steps: 

      - task: TerraformInstaller@1
        inputs:
          terraformVersion: 'latest'

      - task: TerraformTask@5
        displayName: "TerraformInitTask"
        inputs:
          provider: 'azurerm'
          command: 'init'
          backendServiceArm: 'ADOToSubscription'
          backendAzureRmResourceGroupName: 'movie-explorer-rg'
          backendAzureRmStorageAccountName: 'lewisfuncstorage'
          backendAzureRmContainerName: 'tfstate'
          backendAzureRmKey: 'tfstate/movieexplorer-prod.tfstate'
          commandOptions: >
            -upgrade
            -reconfigure
            -var sql_admin_username=$(sqlusername)
            -var sql_admin_password=$(sqlpassword)
            -var subscription_id=$(subscription_id)
          workingDirectory: 'Terraform/'


      - task: TerraformTask@5
        displayName: "TerraformShowTask"
        inputs:
          provider: 'azurerm'
          command: 'show'
          environmentServiceNameAzureRM: 'ADOToSubscription'
          backendServiceArm: 'ADOToSubscription'
          backendAzureRmResourceGroupName: 'movie-explorer-rg'
          backendAzureRmStorageAccountName: 'lewisfuncstorage'
          backendAzureRmContainerName: 'tfstate'
          backendAzureRmKey: 'tfstate/movieexplorer-prod.tfstate'  # 👈 match exact blob name
          workingDirectory: 'Terraform/'


      - task: TerraformTask@5
        displayName: "TerraformDestroyTask"
        inputs:
          provider: 'azurerm'
          command: 'destroy'
          environmentServiceNameAzureRM: 'ADOToSubscription'
          backendServiceArm: 'ADOToSubscription'
          backendAzureRmResourceGroupName: 'movie-explorer-rg'
          backendAzureRmStorageAccountName: 'lewisfuncstorage'
          backendAzureRmContainerName: 'tfstate'
          backendAzureRmKey: 'tfstate/movieexplorer-prod.tfstate'
          commandOptions: >
            -var sql_admin_username=$(sqlusername)
            -var sql_admin_password=$(sqlpassword)
            -var subscription_id=$(subscription_id)
            -auto-approve
          workingDirectory: 'Terraform/'
