# A gated pipelines to destroy all infrastructure created by the deploy-infra pipeline.

trigger:
  none

variables:
  environment: 'prod'

stages:
  - stage: DestroyInfra
    jobs:
    - job: Terraform_Destroy_Job
      steps: 

      - task: TerraformInstaller@1
        inputs:
          terraformVersion: 'latest'
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'init'
          backendServiceArm: 'ADOToSubscription'
          backendAzureRmResourceGroupName: 'movie-explorer-rg'
          backendAzureRmStorageAccountName: 'lewisfuncstorage'
          backendAzureRmContainerName: 'tfstate'
          backendAzureRmKey: 'tfstate/movieexplorer-prod.tfstate'

      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'destroy'
          environmentServiceNameAzureRM: 'ADOToSubscription'
          backendServiceArm: 'ADOToSubscription'
          backendAzureRmResourceGroupName: 'movie-explorer-rg'
          backendAzureRmStorageAccountName: 'lewisfuncstorage'
          backendAzureRmContainerName: 'tfstate'
          backendAzureRmKey: 'tfstate/movieexplorer-prod.tfstate'
