trigger:
  none
pool:
  vmImage: 'ubuntu-latest'
variables:
- name: dockerRegistry
  value: 'lewisacr.azurecr.io'
- name: backendImageName
  value: 'movieexplorer-backend'
- name: frontendImageName
  value: 'movieexplorer-frontend'
stages:
- stage: BuildAndPush
  displayName: "Build and Push Docker Images"
  jobs:
  - job: DockerJob
    displayName: "Build and Push Backend and Frontend"
    steps:
    - task: Docker@2
      displayName: "Build and Push Backend (AMD64)"
      inputs:
        command: 'buildAndPush'
        repository: '$(backendImageName)'
        dockerfile: 'movieexplorer-backend-api/Dockerfile'
        buildContext: 'movieexplorer-backend-api'
        tags: |
          latest
        arguments: '--platform linux/amd64'
        containerRegistry: 'lewisacr'
    - task: Docker@2
      displayName: "Build and Push Frontend (AMD64)"
      inputs:
        command: 'buildAndPush'
        repository: '$(frontendImageName)'
        dockerfile: 'movieexplorer-frontend/dockerfile'
        buildContext: 'movieexplorer-frontend'
        tags: |
          latest
        arguments: '--platform linux/amd64'
        containerRegistry: 'lewisacr'

    - script: |
        IP=$(az webapp show \
          --name MovieExplorerAppBackend \
          --resource-group movie-explorer-rg \
          --query outboundIpAddresses -o tsv)

        az sql server firewall-rule create \
          --resource-group movie-explorer-rg \
          --server sql-server-lewis-test \
          --name AllowAppService \
          --start-ip-address $IP \
          --end-ip-address $IP
      displayName: "Add App Service IP to SQL Firewall"

